#include<stdio.h>
#include<conio.h>
void main()
{
	printf("#######");
	printf("\n#");
	printf("\n#");
	printf("\n####");
	printf("\n#");
	printf("\n#");
	printf("\n#");
	printf("\n");
	printf("\n#######");
	printf("\n#");
	printf("\n#");
	printf("\n#");
	printf("\n#");
	printf("\n#");
	printf("\n#######");
}
